### ISSUE TITLE
Elite Enemies 

### ISSUE THREAD

**Issue by CarrotKutay** [CarrotKutay/UnrealGame#12]
### TODO
- [ ] will be of the same enemy type #9  but will own better stats #10 
- [ ] will drop the skill that they use #
- [ ] will drop upgrades to stats #10
