### ISSUE TITLE
Create Skill(s) + Skill Progression

### ISSUE THREAD

**Issue by CarrotKutay** [CarrotKutay/UnrealGame#13]
### TODO
- [ ] create skill ideas
- [ ] make them drop-able by enemies
- [ ] make them progress-able

-> Find solutions for players:
* [ ] how will skills be dropped (drop chance, or drop at event?)
   -> enemies with a skill will be marked to drop said skill 
* [ ] how can they progress?
