### ISSUE TITLE
Item design

### ISSUE THREAD

**Issue by CarrotKutay** [CarrotKutay/UnrealGame#16]
_WE WANT ITEMS_
### TODO
* [ ] find assets for items (not displayed in fight for now)
   * [ ] weapons 
   * [ ] armor
* [ ] make items possible to pick up -> give them a range where they can be picked up from
* [ ] add slots to player where he can hold items of a certain type
     -> communicate with #10 #7
