### ISSUE TITLE
Player character design

### ISSUE THREAD

**Issue by CarrotKutay** [CarrotKutay/UnrealGame#7]
### TODO
- [ ] find asset for character
  - make it slightly different looking for different players 
- [ ] implement movement (if not already existing in template)
  - not implicitly animations
  - take over animations from assets if possible
  - check compatibility with game-pad movement
- [ ] implement pick up system for items and skills
- [ ] implement level up possibility
- [ ] implement stats for character (life, attack power, etc)
   - MVP: life, attack power, attack speed

**Comment by Kreunus** [comment]
https://www.unrealengine.com/marketplace/en-US/free?count=20&sortBy=effectiveDate&sortDir=DESC&start=0&tag=533

**Comment by Kreunus** [comment]
In Bezug auf den Link. Die Chraktere haben eigene Animationen, Effekte und reisige Texture. Bisher habe ich das ausgelassen, aber werde es noch probieren - ist ja nur Nice to have. Ansonsten können wir einfach den Charakter verweden, den uns Unreal anbietet.

Eine Sache, wenn ich das pushen soll bräuchte ich dazu noch das lsf Feature... werde das noch ein Mal probieren. @CarrotKutay du hast das schon Mal verwendet oder?
