### ISSUE TITLE
Multiplayer Control

### ISSUE THREAD

**Issue by CarrotKutay** [CarrotKutay/UnrealGame#8]
### TODO
* [ ] add possibility for multiple players to play in game
-> see #7 for movement compatibility between keyboard and game-pad issue 

nice to have feature
* [ ] group leader election
* [ ] main camera will follow group leader
